#pragma config(Sensor, S1,     colorSensorA,   sensorColorNxtFULL)
#pragma config(Sensor, S2,     colorSensorB,   sensorNone)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// void leftparking()// did all this assuming motorA is left, motorB is right, colorSensorA is left, colorSensorB is right
task leftparking()
	{
		if (SensorValue(sonarSensor) <= 75)
			{
				motor[motorA] = 90;                                          // lego group x*y x=diamter, y=width
				motor[motorB] = 90;
		 	}
		else
			{
				motor[motorA] = 0;
				motor[motorB] = 90;
				wait1Msec(100);
				nMotorEncoder[motorA] = 0;
				nMotorEncoder[motorB] = 0;
				motor[motorA] = 70;
				motor[motorB] = 70;
				nMotorEncoderTarget[motorA] = 2122;
				nMotorEncoderTarget[motorB] = 2122;
			}
	}
task rightparking()
	{
		if(SensorValue(sonarSensor) <= 75)
			{
				motor[motorA] = 90; // lego group x*y x=diamter, y=width
				motor[motorB] = 90;
		 	}
		else
			{
				motor[motorA] = 90;
				motor[motorB] = 0;
				wait1Msec(100);
				nMotorEncoder[motorA] = 0;
				nMotorEncoder[motorB] = 0;
				motor[motorA] = 70;
				motor[motorB] = 70;
				nMotorEncoderTarget[motorA] = 2122;
				nMotorEncoderTarget[motorB] = 2122;
			}
	}
task main()
	{
		if (SensorValue(colorSensorA)>60) // Don't know what color blue is. 60 I think?
		{
			motor[motorA] = 0;
			motor[motorB] = 0;
			startTask leftparking();
		}
		else if (SensorValue(colorSensorB) > 60);
		{
			motor[motorA] = 0;
			motor[motorB] = 0;
			startTask rightparking();
		}
		else
		{
			motor[motorA] = 90; // I don't know normal speed of robot
			motor[motorB] = 90;
	}
