#pragma config(Sensor, S1,     sensorL,        sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     sensorF,        sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     sensorR,        sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sensorD,        sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorL,        tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          motorR,        tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          motorSonar,    tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// writeDebugStream() is printf()
// Black is 7, red is 60, white is 75, and blue is 12

// 1 for turn left, 2 for turn right, 3 for go straight
// 4 for turn onto a circular path, 5 for move on a circular path
// 6 for the special circular path ( bottom left )
int arr[6] = {1, 2, 3, 4, 5, 6};

void moveForward(bool detection, bool isParking);
void turn(char a, bool isParking);
void circularForward();
void turnOntoCircular();
void specialCircular();
void parking();
task checkCollision();

task main(){
	startTask(checkCollision);
	int index;
	int length = sizeof(arr) / 2; //divide by 2 for int, divide by 20 for string
	for(index = 0; index < length - 1; index++){
		int a = arr[index];
		switch(a){
			case 1:
				turn('l', false);
				break;
			case 2:
				turn('r', false);
				break;
			case 3:
				moveForward(true, false);
				break;
			case 4:
				turnOntoCircular();
				break;
			case 5:
				circularForward();
				break;
			case 6:
				specialCircular();
				break;
		}
	}
	// Last turn and then park
	int b = arr[length - 1];
	switch(b){
		case 1:
			turn('l', true);
			break;
		case 2:
			turn('r', true);
			break;
		case 3:
			moveForward(true, true);
			break;
	}
	// parking
	parking();
}

// put false to skip object detection
void moveForward(bool detection, bool isParking){
	/*
	if(detection){
		// object detection
	}
	*/
	motor[motorL] = 75;
	motor[motorR] = 75;

	wait1Msec(500); // wait for the robot to leave the red line

	if(isParking) return;

	while(!(SensorValue[sensorF] > 55 && SensorValue[sensorF] < 65)){ // while it is not red
		motor[motorL] = 75;
		motor[motorR] = 75;
	}

	motor[motorL] = 0;
	motor[motorR] = 0;
}

// 'l' for left, other for right
void turn(char a, bool isParking){
	// object detection

	motor[motorL] = 25;
	motor[motorR] = 25;
	wait1Msec(1000); // move a distance (we need to test)

	if(a == 'l'){ // turn
		motor[motorL] = -75;
		motor[motorR] = 75;
	} else {
		motor[motorL] = 75;
		motor[motorR] = -75;
	}
	wait1Msec(1000); // we need to test this time

	moveForward(false, isParking);
}

void circularForward(){
	motor[motorL] = 50; // we need to test these numbers
	motor[motorR] = 75;

	wait1Msec(500); // wait for the robot to leave the red line

	while(!(SensorValue[sensorF] >= 58 && SensorValue[sensorF] <= 62)){ // while it is not red
		motor[motorL] = 50; // these numbers should be the same as above
		motor[motorR] = 75;
	}

	motor[motorL] = 0;
	motor[motorR] = 0;
}

void turnOntoCircular(){
	// object detection left

	motor[motorL] = 25;
	motor[motorR] = 25;
	wait1Msec(1000); // move a distance (we need to test)

	motor[motorL] = 75;
	motor[motorR] = -75;
	wait1Msec(1000); // we need to test this time

	circularForward();
}

void specialCircular(){
	// object detection right

	motor[motorL] = 25;
	motor[motorR] = 25;
	wait1Msec(1000); // move a distance (we need to test)

	motor[motorL] = -75;
	motor[motorR] = 75;
	wait1Msec(1000); // we need to test this time

	motor[motorL] = 75; // we need to test these numbers
	motor[motorR] = 60;

	while(!(SensorValue[sensorF] > 55 && SensorValue[sensorF] < 65)){ // while it is not red
		motor[motorL] = 75; // these numbers should be the same as above
		motor[motorR] = 60;
	}

	motor[motorL] = 0;
	motor[motorR] = 0;
}

// return 0 if blue is not found, 1 if blue is left, 2 if blue is right
int whereIsBlue(){
	if(SensorValue[sensorL] >= 10 && SensorValue[sensorL] <= 14)
		return 1;
	else if(SensorValue[sensorR] >= 10 && SensorValue[sensorR] <= 14) // may have some issue with parking lot 9 and 10
		return 2;
	else return 0;
}

void parking(){
	int a = 0;
	while(a == 0){
		wait1Msec(10);
		a = whereIsBlue();
	}
	motor[motorL] = 0;
	motor[motorR] = 0;

	/* Turn the sonar sensor and check objects
		 Or turn the whole robot
	if(SensorValue(sonarSensor) <= 75){
		motor[motorL] = 75;
		motor[motorR] = 75;
	} else{
		motor[motorL] = 0; or 90
		motor[motorR] = 90; or 0
		wait1Msec(100);
		setMotorTarget(motorL, 2122, 75);
		setMotorTarget(motorR, 2122, 75);
		waitUntilMotorStop(motorR);
		motor[motorL] = 0;
		motor[motorR] = 0;
	}
	*/

	// Assume the robot itselt is not turned by this time
	suspendTask(checkCollision);
	if(a == 1){ // turn
		motor[motorL] = 75;
		motor[motorR] = -75;
	} else {
		motor[motorL] = -75;
		motor[motorR] = 75;
	}
	wait1Msec(1000); // we need to test this time

	motor[motorL] = -50;
	motor[motorR] = -50;
	wait1Msec(500);
	while(!(SensorValue[sensorF] >= 10 && SensorValue[sensorF] <= 14)){ // while the front is not blue
		motor[motorL] = -50;
		motor[motorR] = -50;
	}
	motor[motorL] = 0;
	motor[motorR] = 0;
}

task checkCollision(){
	while(true){
		wait1Msec(10);
		if(motor[motorL] == 0 && motor[motorR] == 0){
			continue;
		}

		if(SensorValue[sensorD] < 10){
			suspendTask(main);
			int l = motor[motorL];
			int r = motor[motorR];
			motor[motorL] = 0;
			motor[motorR] = 0;
			wait1Msec(2000);
			motor[motorL] = l;
			motor[motorR] = r;
			startTask(main);
		}
	}
}

// not sure how this works
task sonarFunction(){
	while(true){
		setMotorTarget(motorC, 90, 50);
		waitUntilMotorStop(motorC);
		setMotorTarget(motorC, -90, -50);
		waitUntilMotorStop(motorC);
		motor[motorC] = 0;
	}
}
