#pragma config(Sensor, S1,     sensorL,        sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     sensorF,        sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     sensorR,        sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sensorD,        sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorL,        tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          motorR,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// writeDebugStream() is printf()
// 1 for turn left, 2 for turn right, 3 for go straight
// 4 for turn onto a circular path, 5 for move on a circular path
// 6 for the special circular path ( bottom left )
int arr[6] = {1, 2, 3, 4, 5, 6};

void moveForward();
void turn(char a);
void circularForward();
void turnOntoCircular();
void specialCircular();

task main(){
	int index;
	int length = sizeof(arr) / 2; //divide by 2 for int, divide by 20 for string
	for(index = 0; index < length - 1; index++){
		int a = arr[index];
		switch(a){
			case 1:
				turn('l');
				break;
			case 2:
				turn('r');
				break;
			case 3:
				moveForward();
				break;
			case 4:
				turnOntoCircular();
				break;
			case 5:
				circularForward();
				break;
			case 6:
				specialCircular();
				break;
		}
	}
	int b = arr[length - 1];
	// Turn/Straight then start parking
}

void moveForward(){
	motor[motorL] = 75;
	motor[motorR] = 75;

	wait1Msec(500); // wait for the robot to leave the red line

	while(!(SensorValue[sensorF] > 55 && SensorValue[sensorF] < 65)){ // while it is not red
		motor[motorL] = 75;
		motor[motorR] = 75;
	}

	motor[motorL] = 0;
	motor[motorR] = 0;
}

// 'l' for left, other for right
void turn(char a){
	// object detection

	motor[motorL] = 25;
	motor[motorR] = 25;
	wait1Msec(1000); // move a distance (we need to test)

	if(a == 'l'){ // turn
		motor[motorL] = -75;
		motor[motorR] = 75;
	} else {
		motor[motorL] = 75;
		motor[motorR] = -75;
	}
	wait1Msec(1000); // we need to test this time

	moveForward();
}

void circularForward(){
	motor[motorL] = 50; // we need to test these numbers
	motor[motorR] = 75;

	wait1Msec(500); // wait for the robot to leave the red line

	while(!(SensorValue[sensorF] > 55 && SensorValue[sensorF] < 65)){ // while it is not red
		motor[motorL] = 50; // these numbers should be the same as above
		motor[motorR] = 75;
	}

	motor[motorL] = 0;
	motor[motorR] = 0;
}

void turnOntoCircular(){
	// object detection left

	motor[motorL] = 25;
	motor[motorR] = 25;
	wait1Msec(1000); // move a distance (we need to test)

	motor[motorL] = 75;
	motor[motorR] = -75;
	wait1Msec(1000); // we need to test this time

	circularForward();
}

void specialCircular(){
	// object detection right

	motor[motorL] = 25;
	motor[motorR] = 25;
	wait1Msec(1000); // move a distance (we need to test)

	motor[motorL] = -75;
	motor[motorR] = 75;
	wait1Msec(1000); // we need to test this time

	motor[motorL] = 75; // we need to test these numbers
	motor[motorR] = 60;

	while(!(SensorValue[sensorF] > 55 && SensorValue[sensorF] < 65)){ // while it is not red
		motor[motorL] = 75; // these numbers should be the same as above
		motor[motorR] = 60;
	}

	motor[motorL] = 0;
	motor[motorR] = 0;
}

/*
bool collision(){
if(getUSDistance(sensorD) < 10)
	return true;
return false;
}
*/
