#pragma config(Sensor, S1,     SensorL,        sensorColorNxtFULL)
#pragma config(Sensor, S2,     SensorM,        sensorColorNxtFULL)
#pragma config(Sensor, S3,     SensorR,        sensorColorNxtFULL)
#pragma config(Sensor, S4,     SensorSonar,    sensorSONAR)
#pragma config(Motor,  motorA,          motorL,        tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          motorR,        tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int white = 6;
int green = 3;
int black = 1;

int current1 = motor[motorL];

task adjustL(){
	while(SensorValue(SensorL) == green){
		motor[motorL] += 5;
	}

	while(SensorValue(SensorL) == black){
		motor[motorL] -= 5;
	}
	motor[motorL] = current1;
}

task main(){

	while (true){
		if(SensorValue(SensorL) != white){
			startTask(adjustL);
		}
	}
}
